export default {
  Action: "Action",
  Amount: "Amount",
  Comment: "Comment",
  Frequency: "Frequency",
  Goal: "Goal",
  Modality: "Modality",
  Patient: "Patient",
  Portion: "Portion",
  Professionals: "Professionals",
  Admin: "Admin",
  Rubric: "Rubric",
  Template: "Template",
  Type: "Type",
  Metadata: "Metadata",
};
